### ISSUE TITLE
Build failure on Ubuntu 20.04

### ISSUE THREAD

**Issue by tbpringle** [SophistSolutions/Stroika#116]
bmp@Lion:~/dvl/Stroika$ time make all
Checking Prerequisites for Stroika:
   Checking-Prerequisite Tools Stroika ThirdPartyComponents {Debug}:
      curl 7.70.0 - Checking Prerequisite tools ... done
      lzma 1604 - Checking Prerequisite tools ... done
      sqlite 3320100 - Checking Prerequisite tools ... done
      Xerces 3.2.3 - Checking Prerequisite tools ... done
   Checking-Prerequisite Tools Stroika ThirdPartyComponents {Release}:
      curl 7.70.0 - Checking Prerequisite tools ... done
      lzma 1604 - Checking Prerequisite tools ... done
      sqlite 3320100 - Checking Prerequisite tools ... done
      Xerces 3.2.3 - Checking Prerequisite tools ... done
Building Stroika all {Debug}:
   Stroika ThirdPartyComponents Build {Debug}:
      Stroika/ThirdPartyComponents/zlib Build 1.2.8 {Debug}:
         wget --quiet --no-check-certificate --tries=2 -O ../Origs-Cache/zlib-1.2.8.tar.gz https://github.com/madler/zlib/archive/v1.2.8.tar.gz ... 
         zlib 1.2.8 - Extracting ../Origs-Cache/zlib-1.2.8.tar.gz to CURRENT ... 
         zlib 1.2.8 - Extracting ../Origs-Cache/zlib-1.2.8.tar.gz to IntermediateFiles/Debug/ThirdPartyComponents/zlib ... 
         zlib 1.2.8 - Configure (see IntermediateFiles/Debug/ThirdPartyComponents/zlib//CONFIGURE.OUT) ...
         zlib 1.2.8 - Build (see IntermediateFiles/Debug/ThirdPartyComponents/zlib//BUILD.OUT) ...
         zlib 1.2.8 - Checking ...  Stroika/ThirdPartyComponents/zlib -    [Succeeded]
      Stroika/ThirdPartyComponents/boost Build 1_73_0 {Debug}:
         wget --quiet --no-check-certificate --tries=2 -O ../Origs-Cache/boost_1_73_0.tar.gz https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz ... 
            failed
         WARNING: mirror failed, so retrying:
         wget --quiet --no-check-certificate --tries=2 -O ../Origs-Cache/boost_1_73_0.tar.gz ftp://ftp.sophists.com/Pub/Mirror/boost_1_73_0.tar.gz ... 
            failed
         WARNING: mirror failed, so retrying:
         wget --quiet --no-check-certificate --tries=2 -O ../Origs-Cache/boost_1_73_0.tar.gz ftp://ftp.sophists.com/Pub/Mirror/boost_1_73_0.tar.gz ... 
            failed
         WARNING: mirror failed, so retrying:
         wget --quiet --no-check-certificate --tries=2 -O ../Origs-Cache/boost_1_73_0.tar.gz https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz ... 
            failed
         WARNING: mirror failed, so retrying:
         wget --quiet --no-check-certificate --tries=2 -O ../Origs-Cache/boost_1_73_0.tar.gz ftp://ftp.sophists.com/Pub/Mirror/boost_1_73_0.tar.gz ... 
            failed
         WARNING: mirror failed, so retrying:
         wget --quiet --no-check-certificate --tries=2 -O ../Origs-Cache/boost_1_73_0.tar.gz https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.gz ... 
         Failed downloading ../Origs-Cache/boost_1_73_0.tar.gz
make[5]: *** [Makefile:101: ../Origs-Cache/boost_1_73_0.tar.gz] Error 1
make[4]: *** [Makefile:68: all] Error 2
make[3]: *** [Makefile:120: boost] Error 2
make[2]: *** [Makefile:131: all] Error 2
make[1]: *** [Makefile:159: third-party-components] Error 2
make: *** [Makefile:78: all] Error 2

**Comment by LewisPringle** [comment]
Thanks. I uploaded boost_1_73_0.tar.gz To the sophists mirror site.

 

              Lewis.

**Comment by LewisPringle** [comment]
done/fixed
