### ISSUE TITLE
Linking with x86_64 library instead of arm64 on M1 Mac on Monterey 

### ISSUE THREAD

**Issue by tbpringle** [SophistSolutions/Stroika#117]
Pulling either v2.1-Release or v2.1-Dev
make -j10 clobber
make -j10 all
generates...

ld: warning: ignoring file /usr/local/lib/libidn2.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
         Compiling Tests/TestHarness/SimpleClass.cpp ... 
         Compiling Tests/TestHarness/TestHarness.cpp ... 
         Compiling Tests/TestHarness/SimpleClass.cpp ... 
Undefined symbols for architecture arm64:
  "_idn2_check_version", referenced from:
      _Curl_idnconvert_hostname in libcurl.a(libcurl_la-url.o)
  "_idn2_free", referenced from:
      _Curl_free_idnconverted_hostname in libcurl.a(libcurl_la-url.o)
  "_idn2_lookup_ul", referenced from:
      _Curl_idnconvert_hostname in libcurl.a(libcurl_la-url.o)
  "_idn2_strerror", referenced from:
      _Curl_idnconvert_hostname in libcurl.a(libcurl_la-url.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tbpringle** [comment]
building on a different M1 with Monterey seems to work so I'm not sure what is different.

**Comment by tbpringle** [comment]
the only diff I'm aware of is that the working system uses the old M1 vs the new M1-Max

**Comment by LewisPringle** [comment]
on the broken mac - can you try:
   > brew install libidn2
and let me know if that solves the problem?  I can update the dependency checker code if needed. THX.

**Comment by LewisPringle** [comment]
presume fixed since I never heard back
